# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1epsxIEr5pN118Iwumw6HB0CxPW7vvB_l
"""

import numpy as np
import pandas as pd
df = pd.read_csv('/content/penguins_size.csv')
df.head()

from matplotlib import rcParams
import seaborn as sns
sns.distplot(df.body_mass_g)

sns.jointplot(x='culmen_length_mm',y='culmen_depth_mm',data=df)



sns.pairplot(df)

df.describe()

df.isnull().any() #Checking is there any null values in our dataset

df.isnull().sum()

# Code to replace null values in numerical columns with MEDIAN
df['culmen_length_mm'].fillna(df['culmen_length_mm'].median(),inplace=True)
df['culmen_depth_mm'].fillna(df['culmen_depth_mm'].median(),inplace=True)
df['flipper_length_mm'].fillna(df['flipper_length_mm'].median(),inplace=True)
df['body_mass_g'].fillna(df['body_mass_g'].median(),inplace=True)
# Code to replace null values in categorical column with MODE
df['sex'].fillna(df['sex'].mode().iloc[0],inplace=True)
# Now all null values are replaced with median and mode and dealt properly.
df.isnull().any()

sns.boxplot(df.culmen_length_mm)

sns.boxplot(df.culmen_depth_mm)

sns.boxplot(df.flipper_length_mm)

sns.boxplot(df.body_mass_g)

from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df['sex'] = le.fit_transform(df['sex'])
df['species'] = le.fit_transform(df['species'])
df['island'] = le.fit_transform(df['island'])
df.head()

df.corr().species.sort_values(ascending=False)

X=df.drop(columns=['species'],axis=1)
X.head()

Y=df['species']
Y.head()

from sklearn.preprocessing import MinMaxScaler
scale = MinMaxScaler()
X_scaled = pd.DataFrame(scale.fit_transform(X),columns=X.columns)
X_scaled.head()

from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(X_scaled,Y,test_size=0.2,random_state=0)

X_train.shape

X_test.shape

Y_train.shape

Y_test.shape